name: PullRequest
on: pull_request
permissions: {}
jobs:
  ci:
    permissions:
      contents: read # for actions/checkout
      security-events: write # for codeql-action
    uses: ./.github/workflows/ci.yml

  dependency-review:
    name: Security check of added dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout
      pull-requests: write # for actions/dependency-review-action to publish summary
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Dependency review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: always
